name: Run Dockerized Spring Boot App

on:
  schedule:
    # Run every minute
    - cron: "*/1 * * * *"

jobs:
  run-app:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t ns-ann-app .

      # Step 4: Run the container
      - name: Run Docker Container
        run: |
          docker run --rm ns-ann-app
