name: NSE RSS Fetcher

on:
  schedule:
    # Trigger every minute
    - cron: "*/1 * * * *"

jobs:
  rss-fetcher:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Download the last message file
      - name: Download Last Message File
        uses: actions/download-artifact@v3
        with:
          name: last-message
          path: last-message.txt
        continue-on-error: true  # Ignore errors if the artifact doesn't exist

      # Step 3: Build and run the Docker container
      - name: Build and Run Docker Container
        run: |
          docker build -t nse-rss-fetcher .
          docker run --rm -v $PWD/last-message.txt:/app/last-message.txt nse-rss-fetcher

      # Step 4: Upload the updated last message file
      - name: Upload Last Message File
        uses: actions/upload-artifact@v3
        with:
          name: last-message
          path: last-message.txt
