name: NSE RSS Fetcher

on:
  schedule:
    # Trigger every minute
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  rss-fetcher:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Java environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build the project with Maven
      - name: Build with Maven
        run: mvn clean package

      # Step 5: Run the application
      - name: Run the application
        run: java -jar target/ns-ann-1.0.0.jar processRssFeed
